services:
  postgres:
    ports: []
    networks:
      - default

  redis:
    ports: []
    networks:
      - default

  minio:
    ports: []
    networks:
      - default
      - publion_default

  minio-init:
    networks:
      - default

  backend:
    ports: []
    expose:
      - "4000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    networks:
      - default
      - publion_default

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports: []
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    networks:
      - default
      - publion_default

networks:
  publion_default:
    external: true
