export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  partnerRegister: "/register/partner",
  dashboard: "/dashboard",
  bookings: "/dashboard/bookings",
  bookingDetail: (bookingId: string) => `/dashboard/bookings/${bookingId}`,
  dashboardProfile: "/dashboard/profile",
  partnerDashboard: "/dashboard/partner",
  partnerProfile: "/dashboard/partner/profile",
  partnerActivities: "/dashboard/partner/activities",
  partnerActivityNew: "/dashboard/partner/activities/new",
  partnerActivityEdit: (activityId: string) => `/dashboard/partner/activities/${activityId}`,
  partnerActivityRevision: (activityId: string, revisionId: string) =>
    `/dashboard/partner/activities/${activityId}/revisions/${revisionId}`,
  partnerBookings: "/dashboard/partner/bookings",
  partnerVouchers: "/dashboard/partner/vouchers",
  adminDashboard: "/dashboard/admin",
  adminUsers: "/dashboard/admin/users",
  adminDestinations: "/dashboard/admin/destinations",
  adminDestinationDetail: (destinationId: string) => `/dashboard/admin/destinations/${destinationId}`,
  adminCities: "/dashboard/admin/cities",
  adminCityDetail: (cityId: string) => `/dashboard/admin/cities/${cityId}`,
  adminCategories: "/dashboard/admin/categories",
  adminCategoryDetail: (categoryId: string) => `/dashboard/admin/categories/${categoryId}`,
  adminActivities: "/dashboard/admin/activities",
  adminActivityReview: (activityId: string) => `/dashboard/admin/activities/${activityId}`,
  adminActivityRevisions: "/dashboard/admin/activity-revisions",
  adminActivityRevisionReview: (revisionId: string) =>
    `/dashboard/admin/activity-revisions/${revisionId}`,
  adminBookings: "/dashboard/admin/bookings",
  adminPayments: "/dashboard/admin/payments",
  adminReviews: "/dashboard/admin/reviews",
  city: (citySlug: string) => `/things-to-do/${citySlug}`,
  activity: (activitySlug: string) => `/activities/${activitySlug}`,
  checkout: (activitySlug: string) => `/checkout/${activitySlug}`
} as const;
