export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  partnerRegister: "/register/partner",
  dashboard: "/dashboard",
  dashboardProfile: "/dashboard/profile",
  partnerDashboard: "/dashboard/partner",
  partnerProfile: "/dashboard/partner/profile",
  partnerActivities: "/dashboard/partner/activities",
  partnerActivityNew: "/dashboard/partner/activities/new",
  partnerActivityEdit: (activityId: string) => `/dashboard/partner/activities/${activityId}`,
  adminDashboard: "/dashboard/admin",
  adminUsers: "/dashboard/admin/users",
  adminCities: "/dashboard/admin/cities",
  adminCityDetail: (cityId: string) => `/dashboard/admin/cities/${cityId}`,
  adminCategories: "/dashboard/admin/categories",
  adminCategoryDetail: (categoryId: string) => `/dashboard/admin/categories/${categoryId}`,
  adminActivities: "/dashboard/admin/activities",
  adminActivityReview: (activityId: string) => `/dashboard/admin/activities/${activityId}`,
  city: (citySlug: string) => `/things-to-do/${citySlug}`,
  activity: (activitySlug: string) => `/activities/${activitySlug}`,
  checkout: (activitySlug: string) => `/checkout/${activitySlug}`
} as const;
